#TODO: Need to test the use of Output Parser and see if the result can be well-formatted.
requirement_analysis_prompt_config = {
    "context": "You are a veteran Database specialist and an experienced, detailed-oriented consultant. I need you to analyze the user's requirement and output the analyzed result in a JSON format. Put null values for information you don't know. You will have to explain for each property why you chose that value among its corresponding accepted values, in a detailed way that can convince the user.\n",
    "example_input_variables": ["requirement", "analysis_result"],
    "example_template": """
        requirement: {requirement}
        analysis_result: {analysis_result},
    """,
    "prefix": "Here are some examples of requirement and its corresponding analysis result:\n\n",
    "suffix": "\n\nNow, given a new requirement, give me the analysis result:\nrequirement: {requirement}\nanalysis_result:",
    "actual_input_variable": "requirement",
    "examples": [
        {
            "requirement": "Develop a comprehensive health and wellness tracking platform that integrates with wearable devices and mobile applications. The platform would collect and analyze data related to users' physical activity, sleep patterns, nutrition, and mental well-being. It could provide personalized insights, goal recommendations, and progress tracking to help users make informed decisions about their health. Additionally, it may include social features to encourage users to share achievements and support each other in their wellness journeys.",
            "analysis_result": "\$\n    \"data_model\": $\n        \"data_type\": \"StringOrNumber\",\n        \"structured_data\": true,\n        \"time_series\": true,\n        \"relationship_centric\": true,\n    &,\n    \"requirements\": $\n        \"volume\":  \"HIGH\",\n        \"read\": true,\n        \"write\": true,\n        \"update\": no,\n        \"availability\": null,\n    &,\n    \"cost\": $\n        \"commercial_allow\": null\n    &\n&\n\nThe explanation for this output is as follows: \n1. Data model\n- The data type value is StringOrNumber because you will store numbers such as user's burned calories per physical activity, hours of sleep, number as indicator for your mood. \n- The structured data value is true because the data will have to \n- The time series value is true because the metrics measured by each activity needs to be tracked on time, sequentially\n- The relationship centric value is false because there are many relationships between users, physical activities that each user does, types of metrics connected to each physical activity, the metrics valued measured when they do any activities, the progress they make for each activity\n2. Requirements\n- The volume value is HIGH because the metrics data will be a lot\n- The read value is true because you will often have to read the data to extract information to give insights and goal recommendations\n- The write value is true because you need to save the metrics data continuously every time the user performs an activity\n- The update value is no because you won't be able to edit much data besides your personal information and goals, nutrition\n- The availability value is null because you didn't mention anything regarding the DB availability percentage or the allowed downtime for the DB\n3. Cost\n- The commercial allow value is null because you didn't mention anything regarding whether he wants to use an open-source DB or a commercial DB in the requirement"
        },
        {
            "requirement": "Create a subscription service that delivers a curated selection of sustainable and eco-friendly home products to subscribers on a regular basis. The products could include items like reusable household goods, environmentally friendly cleaning supplies, and energy-efficient devices. The subscription service not only introduces customers to sustainable living practices but also contributes to reducing single-use plastics and promoting a greener lifestyle. The service could offer customization options based on users' preferences and values, such as a focus on zero waste or cruelty-free products.",
            "analysis_result": "$\n    \"data_model\": $\n        \"data_type\": \"StringOrNumber\",\n        \"structured_data\": true,\n        \"time_series\": false,\n        \"relationship_centric\": false,\n    &,\n    \"requirements\": $\n        \"volume\": \"MEDIUM\",\n        \"read\": true,\n        \"write\": true,\n        \"update\": true,\n        \"availability\": true,\n    &,\n    \"cost\": $\n        \"commercial_allow\": true\n    &\n&\n\nThe explanation for this output is as follows: \n1. Data model\n- The data type value is StringOrNumber because you will store numbers such as product ID, product quantity, order ID, order date, customer ID, customer address, customer preferences, etc. \n- The structured data value is true because the data will have to be organized in a structured way so that it can be easily queried and analyzed.\n- The time series value is false because the data will not be collected over time.\n- The relationship centric value is false because the data will not be heavily connected to each other.\n2. Requirements\n- The volume value is MEDIUM because the amount of data will not be too large.\n- The read value is true because you will need to read the data to fulfill orders and track customer preferences.\n- The write value is true because you will need to write the data when customers place orders and update their preferences.\n- The update value is true because you will need to update the data when customers change their addresses or preferences.\n- The availability value is true because the database must be available 24/7 so that customers can place orders and track their shipments.\n3. Cost\n- The commercial allow value is true because you will need to use a commercial database to handle the volume of data and the need for high availability.\n"
        },
        {
            "requirement": "Develop a smart home system that integrates with a variety of IoT devices, such as smart thermostats, security cameras, and smart appliances. This system would collect and manage data from these devices, handling a diverse range of data types and sources. NoSQL databases, like Apache CouchDB or Firebase, could be used to store and retrieve data efficiently, especially when dealing with the semi-structured or nested data often associated with IoT devices. The flexibility of NoSQL databases makes it easier to accommodate new types of devices and data as the smart home ecosystem expands.",
            "analysis_result": "$\n    \"data_model\": $\n        \"data_type\": \"StringOrNumber\",\n        \"structured_data\": false,\n        \"time_series\": true,\n        \"relationship_centric\": true,\n    &,\n    \"requirements\": $\n        \"volume\": \"HIGH\",\n        \"read\": true,\n        \"write\": true,\n        \"update\": true,\n        \"availability\": true,\n    &,\n    \"cost\": $\n        \"commercial_allow\": null\n    &\n&\n\nThe explanation for this output is as follows: \n1. Data model\n- The data type value is StringOrNumber because you will store numbers such as temperature, humidity, power consumption, etc. \n- The structured data value is false because the data will not be stored in a traditional relational database format.\n- The time series value is true because the data will be collected over time.\n- The relationship centric value is true because the data will be connected to each other.\n2. Requirements\n- The volume value is HIGH because the amount of data will be large.\n- The read value is true because you will need to read the data to monitor the status of your home.\n- The write value is true because you will need to write the data to control your home.\n- The update value is true because you will need to update the data when the status of your home changes.\n- The availability value is true because the database must be available 24/7 so that you can monitor and control your home.\n3. Cost\n- The commercial allow value is null because you didn't mention anything regarding whether he wants to use an open-source DB or a commercial DB in the requirement\n"
        },
    ]
}

basic_prompt_example_config = {
    "input_variable": "database",
    "template": 
        """You are a veteran Database specialist and an experienced, detailed-oriented consultant.
            You will give a summary of this {database}'s features.
        """
}
