version: "3"

services:
  backend:
    build: backend
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env

  frontend:
    build: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env

volumes:
  data: